name: Node.js Deployment

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the appropriate operating system

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Use the checkout action to fetch your code

      - name: Setup Node.js
        uses: actions/setup-node@v2  # Use the Node.js setup action to set up Node.js environment
        with:
          node-version: '20'  # Specify the Node.js version

      - name: Deploy to Ubuntu
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /var/www/app2/node-backend
            git pull origin main
            npm install
            pm2 restart app.js
            sudo systemctl reload nginx
